append message to enable ondemand endpoint
BuffettCode/buffett-code-api-client-excel pull request #32
Opened 2021-07-26 12:50 UTC by shoe116

従量課金エンドポイントのボタンのしたに注記を追加
https://github.com/BuffettCode/buffett-code-api-client-excel/issues/24

![image](https://user-images.githubusercontent.com/1937233/126991434-febcf9a7-b28d-45cc-9923-39277e655490.png)

2021-07-26 16:19 UTC, shoe116 commented
@akiomik file の差分はどれも visual studio が生成するやつです

2021-07-26 17:22 UTC, shoe116 commented on BuffettCodeAddinRibbon/SettingForm.cs
> +        private void textAPIKey_TextChanged(object sender, EventArgs e)
消してもGUIからいじると復活してしまうっぽいので今回はこのままいきます

2021-07-28 00:15 UTC, akiomik commented on BuffettCodeAddinRibbon/SettingForm.resx
> +従量課金APIを使うことで、現在5年以内の財務数値しか取得できなかったところ、5年より前の財務数値もBCODE関数で取得することができるようになります。
> 現在5年以内の財務数値しか取得できなかったところ

ちょっとだけ日本語が気になりました。「現在〜できなかった」という表現は今までできなかったことが急にできるようになったようなニュアンスが強いけど、利用者からみて時間軸はいつであろうといいので、機能比較を説明した方が伝わりやすいと思います。

例えば:

「月額料金の範囲では5年以内の財務数値しか取得できないところを」

みたいなイメージです。

2021-07-28 00:16 UTC, akiomik approved these changes
コードの差分はOKです。文言はちょっとだけ気になったので検討してもらえると！

2021-07-28 00:49 UTC, shoe116 commented on BuffettCodeAddinRibbon/SettingForm.resx
> +従量課金APIを使うことで、現在5年以内の財務数値しか取得できなかったところ、5年より前の財務数値もBCODE関数で取得することができるようになります。
スプシのやつコピペなんだけど、これアレだな　リリースノートっぽい文言なんだな
直しますわ

2021-07-28 02:37 UTC, shoe116 commented
@akiomik 文言修正と、注記へのlinkを追加しました

2021-07-28 02:39 UTC, akiomik commented on BuffettCodeAddinRibbon/SettingForm.resx
> +財務数値の取得に従量課金のエンドポイントを利用する必要が歩かないかは、エクセルアドイン内部で都度判定します。
「歩かないかは」 -> 「あるかないかは」

2021-07-28 02:40 UTC, akiomik commented on BuffettCodeAddinRibbon/SettingForm.resx
> +財務数値の取得に従量課金のエンドポイントを利用する必要が歩かないかは、エクセルアドイン内部で都度判定します。
> エクセルアドイン内部で都度判定します

これは「バフェット・コードが判定します」よりわかりやすいくていいと思う 👍

2021-07-28 02:43 UTC, akiomik requested changes
typoだけ直して欲しい

2021-07-28 03:21 UTC, akiomik commented on BuffettCodeAddinRibbon/SettingForm.resx
> +財務数値の取得に従量課金のエンドポイントを利用する必要の有無は、エクセルアドイン内部で都度判定します。
細かいけど、「〜の有無は」となる場合は「必要性の有無は」としないとちょっと日本語としては不自然かなと思う。

一応別の言い換え案も載せておきます。

- 「従量課金エンドポイントの利用の要否は」
- 「従量課金エンドポイントを利用する必要があるかないかは」
- 「従量課金エンドポイントを利用する必要があるかどうかの判定は、エクセルアドイン内部で都度行います」

(文字の接続が多いので、従量課金のエンドポイントの「の」はない方が読みやすい気がする)

2021-07-28 03:22 UTC, akiomik approved these changes

2021-07-28 03:33 UTC, merged