Faster csv download
BuffettCode/buffett-code-api-client-excel pull request #44
Opened 2021-11-01 11:04 UTC by shoe116

to close: https://github.com/BuffettCode/buffett-code-api-client-excel/issues/34
非同期処理の制御がうまくいっていなかったために deadlock 

- [ ] 複雑化していた非同期処理を `ApiClientCore` のみで行うようにする
- [ ] Asyncの設定をキチンと引き継ぐ 
- [ ] 開発者設定から並列実行数の設定を削除
![image](https://user-images.githubusercontent.com/1937233/139661778-19272275-ab26-495a-9dfc-d88455151ae0.png)

2021-11-01 11:15 UTC, shoe116 reviewed
@akiomik これで UDF も CSV DLもサクサク動くようになります

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCore.cs
> +        public void Dispose()
constructor で `httpClient` を作ってるので、せっかくなので `IDisposable` にします

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCore.cs
> +    public class ApiClientCore : IDisposable
こいつだけ非同期で動きます

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCoreWithCache.cs
> +                return apiClientCore.Get(request, isConfigureAwait).Result;
この時点で取得して動くようにします。当然ながら cache からは常に `string` が返ってくるので、こっちのが全体として違和感がないと思う。

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAPIClient/BuffettCodeApiV2Client.cs
> +        public JObject GetQuarter(string ticker, FiscalQuarterPeriod period, bool useOndemand, bool isConfigureAwait = true, bool useCache = true)
`ApiClientCoreWithCache` が同期的に動くようになったので、ここも `Json` をそのまま返します

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAddinRibbon/SettingForm.cs
> +        private void TextAPIKey_TextChanged(object sender, EventArgs e)
命名規則で怒られてたので、大文字始まりにしておきました

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAddinRibbon/SettingForm.cs
> -            var maxDegreeOfParallelism = setting.MaxDegreeOfParallelism;
並行実行を渡す開発者オプションを削除します

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeIO/Resolver/PeriodSupportedTierResolver.cs
> +        public SupportedTier Resolve(DataTypeConfig dataType, string ticker, IPeriod period, bool isConfigureAwait, bool useCache)
`isConfigureAwait` と `useCache` を外からの渡せるように変更しています

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeIOTests/ApiTaskHelperTests.cs
> +            Assert.AreEqual(SupportedTier.FixedTier, helper.FindAvailableTier(DataTypeConfig.Quarter, ticker, fixedOldest, true, true, true));
test は 両方とも true の、 UDF と同じ仕様で動かします

2021-11-01 11:15 UTC, shoe116 commented on BuffettCodeAddinRibbon/CsvDownload/ApiResourceGetter.cs
> +                            (r => processor.GetApiResources(DataTypeConfig.Quarter, parameters.Ticker, r.From, r.To, false, true)
ここを `true` で渡すと、リボンから呼ぶとすごく遅くなるので `false` にします
https://devblogs.microsoft.com/dotnet/configureawait-faq/#why-would-i-want-to-use-configureawaitfalse

2021-11-01 11:39 UTC, shoe116 commented on BuffettCodeCommon/Configuration.cs
> -        private static readonly uint MaxDegreeOfParallelismDefault = 8;
最大同時実行数を設定から消します

2021-11-03 02:36 UTC, akiomik requested changes
単体テストで実APIを呼び出すのは単体テストの責務から外れてるように感じるので、モックを使うように書き直して欲しいです 🙏

2021-11-03 06:46 UTC, shoe116 commented
@akiomik 異常系については mock にできました。
正常系はだいぶ書き直しが必要なので、このPRを merge、リリース後下記で取り組みます
https://github.com/BuffettCode/buffett-code-api-client-excel/issues/45

2021-11-03 06:50 UTC, shoe116 reviewed
@akiomik ApiClientCore を mock できるようにしました

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCore.cs
> +    public class ApiClientCore : IDisposable, IApiClientCore
実際にhttp通信を行うこいつを差し替えられるようにします

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCoreWithCache.cs
> -        public static ApiClientCoreWithCache Create(string apiKey, Uri baseUrl, MemoryCache cache)
この `Create` は誰も使ってなかったので削除

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCoreWithCache.cs
> +        public static ApiClientCoreWithCache Create(IApiClientCore apiClientCore, ApiRequestCacheHelper cacheHelper)
代わりにこっちを作りました

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClientTests/ApiClientCoreWithCacheTests.cs
> +            Assert.ThrowsException<BuffettCodeApiClientException>(() => client.Get(request, false, false));
`clientCore` が例外を投げた場合はそのまま投げることを確認しています

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClientTests/ApiClientCoreWithCacheTests.cs
> +            Assert.AreEqual(request.ToString(), client.Get(request, false, false));
cahceを使っても使わなくても、同じ結果が返ることを確認しています

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClientTests/ApiClientCoreWithCacheTests.cs
> +            Assert.AreEqual(request.ToString(), client.Get(request, false, true));
1回目のリクエスト

2021-11-03 06:50 UTC, shoe116 commented on BuffettCodeAPIClientTests/ApiClientCoreWithCacheTests.cs
> +        private static ApiRequestCacheHelper CreateCheHelperForTest()
test ごとにcache helper を作ります。

2021-11-03 06:54 UTC, akiomik commented on BuffettCodeAPIClient/ApiClientCore.cs
> +                var content = response.Content.ReadAsStringAsync().Result;
`ReadAsStringAsync().Result` って危険な呼び出しにみえるけど、非同期処理が未完了だったらブロックしてくれると。

https://docs.microsoft.com/ja-jp/dotnet/api/system.threading.tasks.task-1.result?view=net-5.0#--

2021-11-03 06:55 UTC, akiomik commented on BuffettCodeAPIClient/ApiClientCore.cs
> +            apiKey = apikey;
これは `this.apiKey = apiKey` になってなくても動く？

2021-11-03 07:00 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCore.cs
> +            apiKey = apikey;
うん、testも書いた
あ　引数が小文字だからだ

2021-11-03 07:05 UTC, shoe116 commented on BuffettCodeAPIClient/ApiClientCore.cs
> +            apiKey = apikey;
fixed: https://github.com/BuffettCode/buffett-code-api-client-excel/pull/44/commits/1f6ce5aac0f41ca47845f505671aa10513019846

2021-11-03 07:07 UTC, akiomik commented on BuffettCodeAPIClient/IApiClientCore.cs
> +        Task<string> Get(ApiGetRequest request, bool isConfigureAwait);
`using (var response = await httpClient.GetAsync(path).ConfigureAwait(isConfigureAwait))` しているのでシグニチャは `Task<string>` のまま、と

2021-11-03 07:13 UTC, shoe116 commented on BuffettCodeAPIClient/IApiClientCore.cs
> +        Task<string> Get(ApiGetRequest request, bool isConfigureAwait);
これどうするかすごい迷ったけど、この `ApiClientCore` の通信部分は非同期に呼び出す前提にしておいたほうがいいと思う。

`string` 直接返す client が `Task<string>` に変換して返すのは全然難しくないし

2021-11-03 07:19 UTC, akiomik commented on BuffettCodeAPIClient/IApiClientCore.cs
> +        Task<string> Get(ApiGetRequest request, bool isConfigureAwait);
将来的には非同期クライアントになってるほうがいいと思うので、内部的には半同期みたいな感じでもシグニチャはこのままでいいと思う

2021-11-03 07:36 UTC, akiomik commented on BuffettCodeAPIClientTests/BuffettCodeApiV3ClientTests.cs
> -                (() => client.GetDaily("6502", day, true, true, false));
なるほど、こういうのがそのまま投げてるテストケースか

2021-11-03 07:40 UTC, akiomik commented on BuffettCodeAddinRibbon/CsvDownload/ApiResourceGetter.cs
> +                            (r => processor.GetApiResources(DataTypeConfig.Quarter, parameters.Ticker, r.From, r.To, false, true)
`ConfigureAwait(true)` にしたいケースがほとんど存在しないし (テストが書きやすいくらい？)、基本的に `ConfigureAwait(false)` でハードコードしたほうが安全な気がしてる

2021-11-03 07:43 UTC, shoe116 commented on BuffettCodeAPIClientTests/BuffettCodeApiV3ClientTests.cs
> -                (() => client.GetDaily("6502", day, true, true, false));
そそ、 http 通信のlogic が処理の真ん中に入っちゃってるんだよね。そとから `clientCore` を渡す形の `VxApiClientHelper` みたいなやつを作って、各 client はその static な関数を呼ぶだけにしようと思う

2021-11-03 07:44 UTC, akiomik commented on BuffettCodeAddinRibbon/SettingForm.cs
> +        }
これは勝手に定義されてるやつ？

2021-11-03 07:46 UTC, shoe116 commented on BuffettCodeAddinRibbon/SettingForm.cs
> +        }
そう、勝手に作られる event handler 用の関数

2021-11-03 07:49 UTC, akiomik commented on BuffettCodeIOTests/ApiTaskHelperTests.cs
> +            Assert.AreEqual(SupportedTier.FixedTier, helper.FindAvailableTier(DataTypeConfig.Quarter, ticker, fixedOldest, true, true, true));
CSVダウンロードように、 `ConfigureAwait(false)` のケースもテストしたほうがいいと思う

2021-11-03 07:50 UTC, akiomik commented on BuffettCodeAddinRibbon/CsvDownload/ApiResourceGetter.cs
> +                            (r => processor.GetApiResources(DataTypeConfig.Quarter, parameters.Ticker, r.From, r.To, false, true)
UDFのほうは考慮する必要があるか

2021-11-03 07:52 UTC, akiomik approved these changes

2021-11-03 07:59 UTC, merged